language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

install:
  - go get github.com/XieXianbin/msg-provider
  - go get github.com/toolkits/file
  - go get github.com/issue9/assert

script: 
  - cd msg-provider
  - go test 